---
git:
  depth: 1
language: generic

sudo: false

addons:
  apt:
    packages:
      - git

branches:
  only:
  - master
  - /^.*-stable$/

cache:
  directories:
  - node_modules
  - lib
  - lib-legacy

env:
  matrix:
  - TEST_TYPE="build-dist"
  - TEST_TYPE="check-lockfile"
  - TEST_TYPE="lint"
  - NODE_VERSION="6" TEST_TYPE="test-ci"
  - NODE_VERSION="4" TEST_TYPE="test-ci"

matrix:
  include:
    - env: NODE_VERSION="6" TEST_TYPE="test-ci"
      os: osx
    - env: NODE_VERSION="4" TEST_TYPE="test-ci"
      os: osx

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink git; brew install git; fi
 - git --version

 # install proper node version
 - nvm install ${NODE_VERSION:=6}
 - node --version
 - npm install -g npm@3
 - npm install

script: npm run $TEST_TYPE

