---
git:
  depth: 1
language: generic

sudo: false

addons:
  apt:
    packages:
      - git

branches:
  only:
  - master
  - /^.*-stable$/

cache:
  directories:
  - node_modules
  - lib
  - lib-legacy

env:
  matrix:
  - TEST_TYPE="build-dist"
  - TEST_TYPE="lockfile"
  - TEST_TYPE="lint"
  - NODE_VERSION="6" TEST_TYPE="js"
  - NODE_VERSION="4" TEST_TYPE="js"

matrix:
  exclude:
  - env: TEST_TYPE="build-dist"
    os: osx
  - env: TEST_TYPE="lockfile"
    os: osx
  - env: TEST_TYPE="lint"
    os: osx

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink git; brew install git; fi
 - git --version

 # install proper node version
 - nvm install ${NODE_VERSION:=6}
 - node --version
 - npm install -g npm@3
 - npm install

os:
 - osx
 - linux

script:
 - if [[ "$TEST_TYPE" == "js" ]]; then npm run test-ci; fi
 - if [[ "$TEST_TYPE" == "build-dist" ]]; then npm run build-dist; fi
 - if [[ "$TEST_TYPE" == "lockfile" ]]; then npm run check-lockfile; fi
 - if [[ "$TEST_TYPE" == "lint" ]]; then npm run lint; fi
